using System.Text.Json.Serialization;

namespace VoiceConsultant.FunctionApp.Models;

/// <summary>
/// Feedback generated by the Foundry agent for a conversation, stored in the "insights" container.
/// </summary>
public class InsightDocument
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = System.Guid.NewGuid().ToString();

    /// <summary>Partition key, matches the source conversation's callId.</summary>
    [JsonPropertyName("callId")]
    public string CallId { get; set; } = string.Empty;

    [JsonPropertyName("conversationId")]
    public string ConversationId { get; set; } = string.Empty;

    /// <summary>Unique identifier for this insight.</summary>
    [JsonPropertyName("guid")]
    public string Guid { get; set; } = System.Guid.NewGuid().ToString();

    /// <summary>Whether the agent produced any actionable suggestions.</summary>
    [JsonPropertyName("suggestionDetected")]
    public bool SuggestionDetected { get; set; }

    [JsonPropertyName("suggestions")]
    public List<SuggestionItem> Suggestions { get; set; } = new();

    [JsonPropertyName("summary")]
    public string Summary { get; set; } = string.Empty;

    [JsonPropertyName("generatedAt")]
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>UTC timestamp formatted as yyyyMMddHHmmssfff, used together with Id to build the OneLake file key.</summary>
    [JsonPropertyName("timestamp")]
    public string Timestamp { get; set; } = DateTimeOffset.UtcNow.ToString("yyyyMMddHHmmssfff");

    /// <summary>Unique file key used to name files in the Fabric lakehouse: {Timestamp}_{Id}.</summary>
    [JsonIgnore]
    public string FileKey => $"{Timestamp}_{Id}";
}

/// <summary>
/// A group of suggestions for a single topic raised during the call.
/// </summary>
public class SuggestionItem
{
    [JsonPropertyName("topic")]
    public string Topic { get; set; } = string.Empty;

    [JsonPropertyName("suggestions")]
    public List<string> Suggestions { get; set; } = new();
}
