using System.Text.Json.Serialization;

namespace VoiceConsultant.FunctionApp.Models;

/// <summary>
/// Feedback generated by the Foundry agent for a conversation, stored in the "insights" container.
/// </summary>
public class InsightDocument
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Partition key, matches the source conversation's callId.</summary>
    [JsonPropertyName("callId")]
    public string CallId { get; set; } = string.Empty;

    [JsonPropertyName("conversationId")]
    public string ConversationId { get; set; } = string.Empty;

    /// <summary>Whether the agent detected signs of financial hardship.</summary>
    [JsonPropertyName("hardshipDetected")]
    public bool HardshipDetected { get; set; }

    [JsonPropertyName("issues")]
    public List<string> Issues { get; set; } = new();

    [JsonPropertyName("suggestions")]
    public List<string> Suggestions { get; set; } = new();

    [JsonPropertyName("summary")]
    public string Summary { get; set; } = string.Empty;

    [JsonPropertyName("generatedAt")]
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.UtcNow;
}
