name: 10 Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "bicep/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_NAME: '' # {projectName}
  PROJECT_ABBR: '' # {projectAbbr}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1 # must use v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}s

      - name: Create Resource Group
        run: az group create --name 'rg-${{ env.PROJECT_NAME }}' --location 'eastus2'

      - name: Deploy Bicep
        working-directory: bicep
        run: |
          az deployment group create \
            --name 'deploy-${{ env.PROJECT_NAME }}' \
            --resource-group 'rg-${{ env.PROJECT_NAME }}' \
            --template-file './main.bicep' \
            --parameters './main.bicepparam'
